name: podcast
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.15.1
  webfeed: ^0.4.2
  http: ^0.12.0+2
  provider: ^4.1.3
  path_provider: ^1.6.11
  path: ^1.7.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/night-in-venice.mp3

